# Generated by Django 3.0.7 on 2020-07-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsweredQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('player', models.CharField(max_length=30)),
                ('response', models.CharField(max_length=300)),
            ],
        ),
    ]
