# Generated by Django 3.0.7 on 2020-07-23 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_item'),
        ('home', '0002_movieinfo'),
    ]

    operations = [
    ]
